" Macvim settings
if has('gui_macvim')
  set guifont=Consolas:h13
  set guioptions=-r "Remove the scrollbar
  set guioptions=-R "Remove the scrollbar
  set guioptions=+e "Show graphical tabs

  autocmd! GUIEnter * set vb t_vb= "Disable bell
  set clipboard=unnamed "Yank and paste to and from the clipboard

  macmenu &File.Open\.\.\. key=<nop>
  map <D-o> :CommandT<cr>

endif
