" General
set nocompatible
syntax enable
set number
set encoding=utf-8

" Status bar
set laststatus=2
set showcmd
set ruler

set wildignore=.*

" Whitespace
set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set linespace=3
set expandtab
set smartindent

set tabpagemax=100

" Buffer at top and bottom of file
" when scrolling
set scrolloff=5

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

filetype off

" Map Leader key to ,
let mapleader=","

" tag search location
set tags=./tags,tags;$HOME

" Vundle configuration
" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Colorscheme
Plugin 'altercation/vim-colors-solarized'

" Plugins
Plugin 'mhinz/vim-startify'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'

call vundle#end()

set background=dark
colorscheme default

filetype on
filetype plugin on

" Startify settings
" w for welcome screen
map <leader>w :Startify<cr>
imap jk <Esc>
imap jj <Esc>

" Startify
let g:startify_list_order = [
            \ ['My Sessions:'],
            \ 'sessions',
            \ ['Recently used files'],
            \ 'files',
            \ ['Bookmarks:'],
            \ 'bookmarks',
            \ ]

"New prompt message
let g:vimshell_prompt = ": "
let g:vimshell_user_prompt = "fnamemodify(getcwd(), \":~\")"

"Default editor
let g:vimshell_editor_command = "/usr/local/bin/macvim"
